# Generated by Django 5.0.1 on 2024-02-03 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_dish'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_marathi_name', models.CharField(default=True, max_length=100)),
                ('qty', models.IntegerField(default=1)),
                ('price', models.FloatField(default=0, null=True)),
                ('total_price', models.FloatField(default=0, null=True)),
                ('ordered_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('added_by', models.ForeignKey(default=True, on_delete=django.db.models.deletion.PROTECT, to='hotel.admin')),
                ('dish', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hotel.dish')),
            ],
        ),
    ]
